version: "3"

services:
  app:
    container_name: react-app
    image: react-app
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm rebuild esbuild && yarn dev"
